# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lxapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lxapp
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.1.0'
pod 'SVProgressHUD', '~> 2.2.1'
pod 'SDWebImage/GIF'    
pod 'MJRefresh', '~> 3.1.15.1'
pod 'Qiniu', '~> 7.1.8'


end
